-- Cambridge Pint Finder V8 — Community Mode
-- Run this in Supabase SQL Editor.
-- The browser uses anonymous auth + the anon/publishable key.
-- No individual spend is publicly exposed; only aggregate summary is queried.

create table if not exists public.pub_support_events (
  id bigint generated by default as identity primary key,
  pub_name text not null,
  spend_gbp numeric(10,2) not null default 0 check (spend_gbp >= 0),
  visit_date timestamptz not null default now(),
  user_id uuid not null default auth.uid()
);

alter table public.pub_support_events enable row level security;

-- Anonymous users may add their own event.
create policy "anonymous users can add support events"
on public.pub_support_events
for insert
to anon, authenticated
with check (auth.uid() = user_id);

-- Do NOT expose raw events to the browser.
-- Summary view exposes only aggregate pub-level totals.
create or replace view public.pub_support_summary
with (security_invoker = true)
as
select
  pub_name,
  count(*)::bigint as visits,
  coalesce(sum(spend_gbp),0)::numeric(12,2) as reported_spend
from public.pub_support_events
group by pub_name;

-- The app needs to read the aggregate view.
grant select on public.pub_support_summary to anon, authenticated;
grant insert on public.pub_support_events to anon, authenticated;

-- Optional: prevent direct table reads from the client.
-- No SELECT policy is created on pub_support_events.
